import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-all-orders',
  templateUrl: './all-orders.component.html',
  styleUrls: ['./all-orders.component.scss'],
})
export class AllOrdersComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}

  orders: any[] = [
    {
      id: 1,
      total: 999,
      numItem: 99,
      date: '2023 / 4 / 7',
      products: [
        {
          id: 1,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 1,
        },
        {
          id: 2,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 0.5, 0, 0],
          inCart: true,
          inFavourites: true,
          numCart: 2,
        },
        {
          id: 3,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 3,
        },
        {
          id: 4,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 0.5, 0, 0],
          inCart: true,
          inFavourites: true,
          numCart: 4,
        },
        {
          id: 5,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 5,
        },
      ],
    },
    {
      id: 2,
      total: 999,
      numItem: 99,
      date: '2023 / 4 / 7',
      products: [
        {
          id: 1,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 1,
        },
        {
          id: 2,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 0.5, 0, 0],
          inCart: true,
          inFavourites: true,
          numCart: 2,
        },
        {
          id: 3,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 3,
        },
        {
          id: 4,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 0.5, 0, 0],
          inCart: true,
          inFavourites: true,
          numCart: 4,
        },
        {
          id: 5,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 5,
        },
      ],
    },
    {
      id: 3,
      total: 999,
      numItem: 99,
      date: '2023 / 4 / 7',
      products: [
        {
          id: 1,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 1,
        },
        {
          id: 2,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 0.5, 0, 0],
          inCart: true,
          inFavourites: true,
          numCart: 2,
        },
        {
          id: 3,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 3,
        },
        {
          id: 4,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 0.5, 0, 0],
          inCart: true,
          inFavourites: true,
          numCart: 4,
        },
        {
          id: 5,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 5,
        },
      ],
    },
    {
      id: 6,
      total: 999,
      numItem: 99,
      date: '2023 / 4 / 7',
      products: [
        {
          id: 1,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 1,
        },
        {
          id: 2,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 0.5, 0, 0],
          inCart: true,
          inFavourites: true,
          numCart: 2,
        },
        {
          id: 3,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 3,
        },
        {
          id: 4,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 0.5, 0, 0],
          inCart: true,
          inFavourites: true,
          numCart: 4,
        },
        {
          id: 5,
          name: 'Oppo A96 Dual SIM',
          price: 9188,
          lastPrice: 10000,
          image: 'assets/images/prod-1.jpg',
          discount: 99,
          rating: [1, 1, 1, 1, 1],
          inCart: true,
          inFavourites: false,
          numCart: 5,
        },
      ],
    },
  ];
}
